model_params:
  model_seed: 1258
  name: 'UtilsModel'
  Vec_Len: 11
  Len_prodFeature: 3
  Len_customerFeature: 5

  Num_cusEncoder_midLayer: 2
  cusEncoder_midLayers: [5, 5]

  Num_prodEncoder_midLayer: 2
  prodEncoder_midLayers: [5, 5]

  Num_CrossEffectLayer: 1
  CrossEffectLayers: [10]


data_params:
  data_seed: 2341
  data_path: "data/Markov_10_3ProdF_5CusF"
  name: "Markov_10_3ProdF_5CusF"

  train_amount: 4000

  valid_amount: 200
  
  test_amount: 2000

  device: "gpu"


exp_params:
  exp_seed: 1265

  train_batch_size: 100
  valid_batch_size: 100
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.999

  device: "gpu"
  max_epochs: 200

logging_params:

  log_name: "Markov_10_UtilsModel_2Layers"

  log_save_perEpoch: 20

  log_save_stack: 4

