model_params:
  model_seed: 1258
  name: 'UtilsModel'
  Vec_Len: 11
  Len_prodFeature: 3
  Len_customerFeature: 5

  Num_cusEncoder_midLayer: 1
  cusEncoder_midLayers: [3]

  Num_prodEncoder_midLayer: 1
  prodEncoder_midLayers: [3]

  Num_CrossEffectLayer: 1
  CrossEffectLayers: [5]


data_params:
  data_seed: 2341
  data_path: "data/Markov_10_3ProdF_5CusF"
  name: "Markov_10_3ProdF_5CusF"

  train_amount: 2000

  valid_amount: 200
  
  test_amount: 2000

  device: "gpu"


exp_params:
  exp_seed: 1265

  train_batch_size: 20
  valid_batch_size: 20
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.99

  device: "gpu"
  max_epochs: 250

logging_params:

  log_name: "Markov_10_UtilsModel"

  log_save_perEpoch: 20

  log_save_stack: 2

